### ISSUE TITLE
Issue with fof/upload

### ISSUE THREAD

**Issue by iPurpl3x** [askvortsov1/flarum-rich-text#15]
**Current behavior:** 

```
[upl-image-preview url=https://community.upc.ch/assets/files/2021-10-15/1634293696-507846-landscape-0.jpg

]
```

**Expected behavior:** 

```
[upl-image-preview url=https://community.upc.ch/assets/files/2021-10-15/1634293696-507846-landscape-0.jpg]
```

**Reproduce:**
1. Open composer with Rich Text activated
2. Press SHIFT+ENTER
2. Insert an image with fof/upload (either uploading it or with the media manager)

Flarum: 1.0.4
Rich Text: 2.1.0

**Comment by mtr-static-official** [comment]
I am suffering from the same problem.
Flarum: 1.2.0 
Rich Text: 2.1.1
![image](https://user-images.githubusercontent.com/64729760/153109568-f68687a2-1cdd-4b7d-83d2-18180a1f6b92.png)
Reproduce:

1.Open composer with Rich Text activated
2.Enter any text
3.Insert a picture
