### ISSUE TITLE
Problem with information bubble on firefox

### ISSUE THREAD

**Issue by TB54** [askvortsov1/flarum-rich-text#17]
Hello! Sorry, I'm not used to github, so I don't know if it's the right place, but I just realize there is a problem on firefox.

When you apply H1, H2, H3 to a selected text, the associated tooltip stays "stuck" when it reappears the next time you want to apply another one. It makes that soon, the first ones (H1, H2...) are not accessible anymore, as seen here : 

https://i.imgur.com/g1Rq1WH.png

The problem is not present on chrome.

**Comment by askvortsov1** [comment]
Should be fixed in 1f5ee77d5fbabc41ac83fdcdf7348ce07a680e65, thanks!
