### ISSUE TITLE
Missing tooltip translation

### ISSUE THREAD

**Issue by imorland** [askvortsov1/flarum-rich-text#3]
![image](https://user-images.githubusercontent.com/16573496/120676497-fe406d00-c48d-11eb-8e39-bbfd4b83362c.png)

Looking at https://github.com/flarum/core/blob/11b1ab593226a2412913892d7c7850e0e379dcc1/locale/core.yml#L286

This key should be `core.forum.composer.preview_tooltip`?

**Comment by rob006** [comment]
> This key should be `core.forum.composer.preview_tooltip`?

This translation should not be used directly in the first place. AFAIK every context should use unique key.

https://github.com/askvortsov1/flarum-rich-text/blob/7fe9acf6145fcc5d3b7ec6ca77940a6674f6c5f3/js/src/common/applyEditor.js#L27

Also I'm not sure what is the BC policy for translations in Flarum core. Could Flarum remove some unused keys in minor/patch release? That could break extensions that use these keys.
