### ISSUE TITLE
Images are not rendered when initial upload is completed

### ISSUE THREAD

**Issue by ctml91** [askvortsov1/flarum-rich-text#9]
When uploading an image using fof/upload and using the image markdown template, the raw markdown text is displayed after upload and the preview must be toggled off and back on for it to render the image.

https://discuss.flarum.org/d/26455-wysiwyg-rich-text-editor/167

**Comment by askvortsov1** [comment]
Opened https://github.com/FriendsOfFlarum/upload/pull/295, up to the FoF team now.

**Comment by fanmingfei** [comment]
This problem seems to still exist.
Image not show in editor.
![image](https://user-images.githubusercontent.com/4632277/148087161-2fd1397e-fed0-46be-96ac-7207f5c0a263.png)

**Comment by ctml91** [comment]
You will need to change the template in fof upload using the image markdown template, check the discuss link in main post. The one in your screenshot isn't standard markdown so the editor doesn't know how to handle it. By switching to the other image template in fof/upload it should allow it to render.

**Comment by fanmingfei** [comment]
thanks
